export const ROUTES = {
  HOME: '/',
  MAP: '/map',
  COMMUNITY: '/community',
  PROFILE: '/profile',
  CAT_DETAIL: '/cats/:catId',
  PUBLIC_CAT: '/cats/public/:catId',
  POST_DETAIL: '/posts/:postId',
  FEED: '/feed',
  SIGHTING_SHARE: '/sightings/share/:sightingId',
  SCAN: '/scan',
  GALLERY: '/gallery',
  ADMIN: '/admin',
  BADGES: '/badges',
  NOTIFICATIONS: '/notifications',
  WEEKLY_REPORT: '/weekly-report',
  LOGIN: '/login',
  COLLECTION: '/collection',
  LEAGUE: '/league',
  WRAPPED: '/wrapped',
  ROUTES_PAGE: '/routes',
  CAT_INTEL: '/intel',
}
