# Admin.jsx tabification script
# Generated by Hermes Agent

import os

def main():
    path = os.path.join(os.path.dirname(__file__) or ".", "src", "pages", "Admin.jsx")
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()

    # Step 1: Add TABS constant after RECORD_TYPES
    tabs_block = """
const TABS = [
  { key: "cats", label: "猫档案 🐱" },
  { key: "health", label: "健康 🏥" },
  { key: "feeding", label: "喂食 🍽" },
  { key: "reports", label: "举报 ⚠" },
  { key: "sightings", label: "偶遇 👣" },
]

"""
    content = content.replace("const RECORD_TYPES", tabs_block + "const RECORD_TYPES")

    # Step 2: Add new states
    old_state = "const [selectedCatId, setSelectedCatId] = useState(null)"
    new_states = "const [selectedCatId, setSelectedCatId] = useState(null)
  const [adminTab, setAdminTab] = useState(\"cats\")
  const [healthCatId, setHealthCatId] = useState(null)
  const [healthCatList, setHealthCatList] = useState([])"
    content = content.replace(old_state, new_states)

    print("Part 1 test: TABS insertion OK")

    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

if __name__ == "__main__":
    main()
