/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-dark)',
        'primary-light': 'var(--color-primary-light)',
        mint: '#5EC8A7',
        'mint-hover': '#3FAA86',
        'mint-light': '#E8F7F1',
        'warm-50': 'var(--color-gray-50)',
        'warm-100': '#FFF1E6',
        'cat-orange': 'var(--color-primary)',
        card: 'var(--color-surface)',
        text: 'var(--color-ink)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted': 'var(--color-muted)',
        success: 'var(--color-success)',
        info: 'var(--color-info)',
        warning: 'var(--color-warning)',
        danger: 'var(--color-danger)',
        border: 'var(--color-border)',
        'border-light': 'var(--color-gray-100)',
        'surface-0': 'var(--color-surface-0)',
        'surface-1': 'var(--color-surface)',
        'surface-2': 'var(--color-gray-50)',
        'surface-3': 'var(--color-gray-100)',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      boxShadow: {
        'card': '0 1px 2px 0 rgb(0 0 0 / 0.04)',
        'card-hover': '0 4px 6px -1px rgb(0 0 0 / 0.06), 0 2px 4px -2px rgb(0 0 0 / 0.06)',
        'elevated': '0 10px 15px -3px rgb(0 0 0 / 0.06), 0 4px 6px -4px rgb(0 0 0 / 0.06)',
        'e0': 'none',
        'e1': '0 1px 2px rgb(17 12 9 / 0.04)',
        'e2': '0 2px 8px -2px rgb(17 12 9 / 0.08), 0 1px 2px rgb(17 12 9 / 0.04)',
        'e3': '0 8px 24px -8px rgb(17 12 9 / 0.12), 0 2px 6px -2px rgb(17 12 9 / 0.06)',
        'e4': '0 16px 40px -12px rgb(17 12 9 / 0.16)',
        'primary-glow': '0 8px 24px -4px rgb(249 115 22 / 0.35)',
      },
      fontSize: {
        'display-xl': ['36px', { lineHeight: '1.1', fontWeight: '800' }],
        'display-lg': ['28px', { lineHeight: '1.15', fontWeight: '800' }],
        'h1':         ['22px', { lineHeight: '1.25', fontWeight: '700' }],
        'h2':         ['18px', { lineHeight: '1.3',  fontWeight: '700' }],
        'h3':         ['16px', { lineHeight: '1.4',  fontWeight: '600' }],
        'body':       ['15px', { lineHeight: '1.6',  fontWeight: '400' }],
        'body-sm':    ['14px', { lineHeight: '1.5',  fontWeight: '400' }],
        'caption':    ['12px', { lineHeight: '1.4',  fontWeight: '500' }],
        'overline':   ['11px', { lineHeight: '1.2',  fontWeight: '600' }],
      },
      borderRadius: {
        'tile': '12px',
        'card': '16px',
        'container': '20px',
        'pill': '9999px',
      },
      backgroundImage: {
        'page-warm': 'linear-gradient(180deg, #FFF9F5 0%, #FFF2EA 100%)',
        'hero-morning': 'linear-gradient(135deg, #FFF7ED 0%, #FED7AA 100%)',
      },
    },
  },
  plugins: [],
}
