"""baseline_capture_current_schema

Revision ID: 4cf3161f45b4
Revises: 
Create Date: 2026-06-20 21:11:56.813025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf3161f45b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cat_images_cat_id'), 'cat_images', ['cat_id'], unique=False)
    op.create_index(op.f('ix_post_comments_post_id'), 'post_comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_likes_post_id'), 'post_likes', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_likes_user_id'), 'post_likes', ['user_id'], unique=False)
    op.create_index(op.f('ix_posts_user_id'), 'posts', ['user_id'], unique=False)
    op.create_index(op.f('ix_sightings_cat_id'), 'sightings', ['cat_id'], unique=False)
    op.create_index(op.f('ix_sightings_user_id'), 'sightings', ['user_id'], unique=False)
    op.create_foreign_key(None, 'sightings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sightings', type_='foreignkey')
    op.drop_index(op.f('ix_sightings_user_id'), table_name='sightings')
    op.drop_index(op.f('ix_sightings_cat_id'), table_name='sightings')
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.drop_index(op.f('ix_post_likes_user_id'), table_name='post_likes')
    op.drop_index(op.f('ix_post_likes_post_id'), table_name='post_likes')
    op.drop_index(op.f('ix_post_comments_post_id'), table_name='post_comments')
    op.drop_index(op.f('ix_cat_images_cat_id'), table_name='cat_images')
    # ### end Alembic commands ###
