"""add_missing_columns

Revision ID: d0313e2b50e6
Revises: a1b2c3d4e5f6
Create Date: 2026-06-21 20:53:48.170081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0313e2b50e6'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campus_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cats_campus_id'), ['campus_id'], unique=False)
        batch_op.create_foreign_key('fk_cats_campus_id', 'campuses', ['campus_id'], ['id'])

    with op.batch_alter_table('feeding_check_ins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feeding_check_ins_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('feeding_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campus_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_feeding_points_campus_id'), ['campus_id'], unique=False)
        batch_op.create_foreign_key('fk_feeding_points_campus_id', 'campuses', ['campus_id'], ['id'])

    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_comments_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('post_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_images_post_id'), ['post_id'], unique=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_post_id'), ['post_id'], unique=False)

    with op.batch_alter_table('sightings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sightings_latitude'))
        batch_op.drop_index(batch_op.f('ix_sightings_longitude'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_version', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('campus_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_campus_id'), ['campus_id'], unique=False)
        batch_op.create_foreign_key('fk_users_campus_id', 'campuses', ['campus_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_campus_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_campus_id'))
        batch_op.drop_column('campus_id')
        batch_op.drop_column('token_version')

    with op.batch_alter_table('sightings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sightings_longitude'), ['longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_sightings_latitude'), ['latitude'], unique=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_post_id'))

    with op.batch_alter_table('post_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_images_post_id'))

    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_comments_user_id'))

    with op.batch_alter_table('feeding_points', schema=None) as batch_op:
        batch_op.drop_constraint('fk_feeding_points_campus_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_feeding_points_campus_id'))
        batch_op.drop_column('campus_id')

    with op.batch_alter_table('feeding_check_ins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feeding_check_ins_user_id'))

    with op.batch_alter_table('cats', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cats_campus_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cats_campus_id'))
        batch_op.drop_column('campus_id')

    # ### end Alembic commands ###
