BADGE_CATALOG = [
    {
        "badge_key": "first_sighting",
        "name": "初次偶遇",
        "emoji": "👀",
        "description": "记录第一次校园猫偶遇",
        "series": "sighting",
        "series_name": "偶遇系列",
        "color": "#A8A29E",
        "condition_text": "完成 1 次偶遇记录",
        "order": 1,
        "type": "auto",
        "check_fn": "sightings >= 1",
    },
    {
        "badge_key": "cat_observer",
        "name": "猫猫观察员",
        "emoji": "🔭",
        "description": "持续观察校园猫咪",
        "series": "sighting",
        "series_name": "偶遇系列",
        "color": "#F97316",
        "condition_text": "完成 5 次偶遇记录",
        "order": 2,
        "type": "auto",
        "check_fn": "sightings >= 5",
    },
    {
        "badge_key": "cat_expert",
        "name": "猫猫专家",
        "emoji": "🎯",
        "description": "已经是资深猫猫观察者",
        "series": "sighting",
        "series_name": "偶遇系列",
        "color": "#EAB308",
        "condition_text": "完成 20 次偶遇记录",
        "order": 3,
        "type": "auto",
        "check_fn": "sightings >= 20",
    },
    {
        "badge_key": "first_post",
        "name": "首帖纪念",
        "emoji": "📝",
        "description": "在社区发布了第一条帖子",
        "series": "community",
        "series_name": "社区系列",
        "color": "#A8A29E",
        "condition_text": "发布 1 篇帖子",
        "order": 4,
        "type": "auto",
        "check_fn": "posts >= 1",
    },
    {
        "badge_key": "community_helper",
        "name": "社区热心人",
        "emoji": "💬",
        "description": "积极参与社区讨论",
        "series": "community",
        "series_name": "社区系列",
        "color": "#22C55E",
        "condition_text": "发布 3 篇帖子",
        "order": 5,
        "type": "auto",
        "check_fn": "posts >= 3",
    },
    {
        "badge_key": "community_star",
        "name": "社区之星",
        "emoji": "⭐",
        "description": "社区最活跃的铲屎官",
        "series": "community",
        "series_name": "社区系列",
        "color": "#EAB308",
        "condition_text": "发布 10 篇帖子",
        "order": 6,
        "type": "auto",
        "check_fn": "posts >= 10",
    },
    {
        "badge_key": "cat_collector",
        "name": "猫猫收藏家",
        "emoji": "🏆",
        "description": "认识了校园里的好多猫",
        "series": "collect",
        "series_name": "收集系列",
        "color": "#A8A29E",
        "condition_text": "认识 5 只不同的猫",
        "order": 7,
        "type": "auto",
        "check_fn": "cats_known >= 5",
    },
    {
        "badge_key": "cat_master",
        "name": "猫猫大师",
        "emoji": "👑",
        "description": "认识校园里的每一只猫",
        "series": "collect",
        "series_name": "收集系列",
        "color": "#EAB308",
        "condition_text": "认识全部猫猫",
        "order": 8,
        "type": "auto",
        "check_fn": "cats_known == total_cats",
    },
    {
        "badge_key": "new_cat_finder",
        "name": "新猫发现者",
        "emoji": "🐾",
        "description": "发现了一只新猫咪",
        "series": "special",
        "series_name": "特殊成就",
        "color": "#2DD4BF",
        "condition_text": "提交的新猫线索被审核通过",
        "order": 9,
        "type": "event",
    },
    {
        "badge_key": "photography_first",
        "name": "摄影入门",
        "emoji": "📸",
        "description": "为猫猫拍下了第一张照片",
        "series": "special",
        "series_name": "特殊成就",
        "color": "#A8A29E",
        "condition_text": "上传过至少 1 张照片",
        "order": 10,
        "type": "event",
    },
    {
        "badge_key": "map_explorer",
        "name": "地图探索者",
        "emoji": "🗺️",
        "description": "探索了校园多个猫猫出没点",
        "series": "special",
        "series_name": "特殊成就",
        "color": "#3B82F6",
        "condition_text": "在 3 个不同地点有偶遇记录",
        "order": 11,
        "type": "event",
    },
    {
        "badge_key": "collection_complete",
        "name": "收集全满",
        "emoji": "✨",
        "description": "集齐了全部勋章",
        "series": "special",
        "series_name": "特殊成就",
        "color": "#EAB308",
        "condition_text": "获得其他所有勋章",
        "order": 12,
        "type": "special",
    },
]


def get_badge_catalog():
    return list(BADGE_CATALOG)


def get_badge(badge_key: str):
    for b in BADGE_CATALOG:
        if b["badge_key"] == badge_key:
            return b
    return None


SERIES_ORDER = {"sighting": 0, "community": 1, "collect": 2, "special": 3}
